steps:
- name: bash
  script: |
    - echo $$MARKET_DATA
  secretEnv: ['MARKET_DATA']
availableSecrets:
  secretManager:
    - versionName: projects/549588183482/secrets/market-data
      env: 'MARKET_DATA'
#    #!/usr/bin/env bash
#    echo "=================== Starting"
#    apk -q --no-cache add openjdk11 maven curl gpg
#    ./mvnw -B clean
#    gpg --version

#availableSecrets:
#  secretManager:
#    - versionName: projects/$PROJECT_ID/secrets/mySecret/versions/latest
#      env: 'MYSECRET'