steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    echo "=================== Starting"
    apk --no-cache add openjdk11
    apk --no-cache add maven
    apk --no-cache add curl
    java -version
    #./mvnw clean
    #sdk version
