steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    apk -q --no-cache add openjdk11 maven curl gpg yq
    mkdir -p target
    echo $METALIB-GITHUB-MAVEN > target/metalib.yaml
    yq .MAVEN_GITHUB_USERNAME target/metalib.yaml
  secretEnv: ['METALIB-GITHUB-MAVEN']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/metalib-github-maven/versions/latest
      env: 'METALIB-GITHUB-MAVEN'

# 549588183482@cloudbuild.gserviceaccount.com
#    #!/usr/bin/env bash
#    echo "=================== Starting"
#    apk -q --no-cache add openjdk11 maven curl gpg
#    ./mvnw -B clean
#    gpg --version

#availableSecrets:
#  secretManager:
#    - versionName: projects/$PROJECT_ID/secrets/mySecret/versions/latest
#      env: 'MYSECRET'