steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    apk -q --no-cache add openjdk11 maven curl gpg yq
    export MAVEN_GITHUB_USERNAME=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .MAVEN_GITHUB_USERNAME)
    export MAVEN_GITHUB_PASSWORD=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .MAVEN_GITHUB_PASSWORD)
    export OSSRH_USERNAME=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .OSSRH_USERNAME)
    export OSSRH_PASSWORD=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .OSSRH_PASSWORD)
    export OSSRH_GPG_PASSPHRASE=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .OSSRH_GPG_PASSPHRASE)
    export OSSRH_PUBLIC_KEY=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .OSSRH_PUBLIC_KEY)
    export OSSRH_PRIVATE_KEY=$(echo $METALIB_GITHUB_MAVEN | base64 -d | yq .OSSRH_PRIVATE_KEY)
    echo $OSSRH_PPUBLIC_KEY | gpg --batch --import
  secretEnv: ['METALIB_GITHUB_MAVEN']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/metalib-github-maven/versions/latest
      env: 'METALIB_GITHUB_MAVEN'

# 549588183482@cloudbuild.gserviceaccount.com
#    #!/usr/bin/env bash
#    echo "=================== Starting"
#    apk -q --no-cache add openjdk11 maven curl gpg
#    ./mvnw -B clean
#    gpg --version

#availableSecrets:
#  secretManager:
#    - versionName: projects/$PROJECT_ID/secrets/mySecret/versions/latest
#      env: 'MYSECRET'