steps:
- name: bash
  script: |
    - echo $MARKET_DATA
  secretEnv: ['MARKET_DATA']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/market-data/versions/latest
      env: 'MARKET_DATA'

# 549588183482@cloudbuild.gserviceaccount.com
#    #!/usr/bin/env bash
#    echo "=================== Starting"
#    apk -q --no-cache add openjdk11 maven curl gpg
#    ./mvnw -B clean
#    gpg --version

#availableSecrets:
#  secretManager:
#    - versionName: projects/$PROJECT_ID/secrets/mySecret/versions/latest
#      env: 'MYSECRET'