steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    echo "=================== Starting"
    apk --no-cache add openjdk11 maven curl
    java -version
    mvn -version
    #./mvnw clean
    #sdk version
