name: Build

#on: [workflow_dispatch]
on: [push]

jobs:
  test-project-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install java with maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: import GPG key
        run: |
          mkdir -p ~/.ssh
          echo "$OSSRH_GPG_PRIVATE_KEY" > ~/.ssh/ossrh-gpg-private.txt 
          echo "$OSSRH_GPG_PUBLIC_KEY" > ~/.ssh/ossrh-gpg-public.txt
          cat ~/.ssh/ossrh-gpg-private.txt
          cat ~/.ssh/ossrh-gpg-public.txt
      - name: run `mvn package`
        run: |
          gpg --list-secret-keys
          #./mvnw -B package
    env:
      GITHUB_TOKEN: ${{ github.token }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASWORD }}
      OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      OSSRH_GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
      OSSRH_GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
