name: Build

on: [workflow_dispatch]
#on: [push]

jobs:
  test-project-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install java with maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: import GPG key
        run: |
          echo $OSSRH_GPG_PUBLIC_KEY | base64 -d | gpg --batch --import
          echo $OSSRH_GPG_PRIVATE_KEY | base64 -d | gpg --batch --import
      - name: git config
        run: |
          git config --global user.email "ikatraev@gmail.com"
          git config --global user.name "Igor Katrayev"
      - name: release maven artifact
        run: |
          ./mvnw -X -s ./.mvn/settings.xml release:prepare release:perform -B -DskipTests=true -Djava.security.egd=file:/dev/./urandom -DscmCommentPrefix="[mvn-release] " -Prelease-sign-artifacts
    env:
      GITHUB_TOKEN: ${{ github.token }}
      MAVEN_GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
      MAVEN_GITHUB_PASSWORD: ${{ secrets.MAVEN_GITHUB_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASWORD }}
      OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      OSSRH_GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
      OSSRH_GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
