name: Build

on: [workflow_dispatch]
#on: [push]

jobs:
  test-project-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install java with maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: import GPG key
        run: |
          mkdir -p ~/.ssh
          echo "$OSSRH_GPG_PRIVATE_KEY" > ~/.ssh/ossrh-gpg-private.txt 
          echo "$OSSRH_GPG_PUBLIC_KEY" > ~/.ssh/ossrh-gpg-public.txt
          gpg --batch --import ~/.ssh/ossrh-gpg-public.txt
          echo "$OSSRH_GPG_PASSPHRASE" | gpg --batch --import ~/.ssh/ossrh-gpg-private.txt
      - name: git config
        run: |
          git config --global user.email "ikatraev@gmail.com"
          git config --global user.name "Igor Katrayev"
      - name: release maven artifact
        run: |
          ./mvnw -s ./.mvn/settings.xml release:prepare release:perform -B -DskipTests=true -Djava.security.egd=file:/dev/./urandom -DscmCommentPrefix="[mvn-release] " -Prelease-sign-artifacts
    env:
      GITHUB_TOKEN: ${{ github.token }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASWORD }}
      OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      OSSRH_GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
      OSSRH_GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
