name: Build Test

run-name: ${{ github.actor }} is testing the project build

#on: [push]
on: [workflow_dispatch]

jobs:
  test-project-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install java with maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: run `mvn package`
        run: |
          ./mvnw -B package
